import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import { getTripById } from '@/lib/supabase/queries/trips';
// Phase 4 (legacy) data + components — kept live behind the
// readiness gate so production keeps working until the Phase 5
// migration is applied AND the operator portal v=2 path ships
// (Codex P1 fixes on PR #10).
import { listOffersByTrip } from '@/lib/supabase/queries/phase4-offers';
import { DispatchForm } from '@/components/admin/dispatch-form';
import { Phase4OfferCard } from '@/components/admin/phase4-offer-card';
// Phase 5 (new) data + components — only loaded when the gate
// is on. Reading these against a Supabase project that hasn't
// applied migration 20260505000004 would throw at runtime, so
// the gate must stay off until the migration has been verified.
import { listOffersByTripUnified } from '@/lib/supabase/queries/unified-offers';
import { listCurrentRoundTargets } from '@/lib/supabase/queries/phase5-targets';
import {
  buildOperatorUrl,
  buildOperatorWhatsAppLink,
} from '@/lib/operator/links';
import { issueOperatorTokenFromTarget } from '@/lib/operator/token';
import { TripDetailCard } from '@/components/admin/trip-detail-card';
import {
  DispatchPanelV2,
  type DispatchPanelV2Props,
} from '@/components/admin/dispatch-panel-v2';
import { UnifiedOfferCard } from '@/components/admin/unified-offer-card';
import type { TripRequestRow } from '@/types/database';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export const metadata: Metadata = {
  title: 'تفاصيل الرحلة',
  robots: { index: false, follow: false },
};

interface TripDetailPageProps {
  params: { id: string };
}

/**
 * Readiness gate for the Phase 5 admin UI.
 *
 * Default OFF — production renders the Phase 4 single-operator
 * dispatch + Phase 4-only offers list, identical to what shipped
 * before PR #10. Set `PHASE5_ADMIN_UI=true` in the relevant
 * Vercel environment ONLY when:
 *
 *   1. Migration `20260505000004_phase_5_distribution.sql` has
 *      been applied to that environment's Supabase project (the
 *      Phase 5 page reads `current_dispatch_round_id`,
 *      `trip_dispatch_targets`, and `phase5_operator_offers` on
 *      every render — without the schema this throws), AND
 *   2. The operator portal v=2 path has shipped (PR 5) so v=2
 *      tokens generated by the multi-row dispatch panel
 *      actually validate when the operator opens them.
 *
 * Flipping the gate before BOTH conditions are met is a P1
 * regression. The gate is read on every render (server-side
 * env var); revert by unsetting the env and redeploying.
 */
function phase5UiReady(): boolean {
  return process.env.PHASE5_ADMIN_UI === 'true';
}

export default async function TripDetailPage({ params }: TripDetailPageProps) {
  const trip = await getTripById(params.id);
  if (!trip) {
    notFound();
  }

  if (phase5UiReady()) {
    return <Phase5TripView trip={trip} />;
  }
  return <Phase4TripView trip={trip} />;
}

// ============================================================================
// Phase 4 (legacy) view — default before the gate flips
// ============================================================================

async function Phase4TripView({ trip }: { trip: TripRequestRow }) {
  const offers = await listOffersByTrip(trip.id);

  const isClosed = trip.status === 'booked' || trip.status === 'cancelled';
  const dispatchExpired =
    trip.dispatch_expires_at !== null &&
    Date.parse(trip.dispatch_expires_at) <= Date.now();

  return (
    <section>
      <div className="flex items-center justify-between gap-3">
        <BackLink />
        <AddonsTabLink tripId={trip.id} />
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1.6fr,1fr] lg:items-start">
        <div className="space-y-6">
          <TripDetailCard trip={trip} />

          <div className="rounded-xl border border-border bg-navy-card/40 p-6">
            <div className="flex items-center justify-between gap-3">
              <h3 className="font-ar text-base font-medium text-ink">
                العروض المستلمة ({offers.length})
              </h3>
            </div>
            {offers.length === 0 ? (
              <p className="font-ar mt-4 rounded-md border border-dashed border-border bg-navy-secondary/30 p-6 text-center text-sm text-ink-muted">
                لم يصل أي عرض من المشغّلين بعد.
              </p>
            ) : (
              <div className="mt-4 space-y-4">
                {offers.map((offer) => (
                  <Phase4OfferCard key={offer.id} offer={offer} />
                ))}
              </div>
            )}
          </div>
        </div>

        <aside className="space-y-6">
          <div className="rounded-xl border border-border bg-navy-card/40 p-5">
            <h3 className="font-ar text-base font-medium text-ink">
              إرسال للمشغّل
            </h3>
            {isClosed ? (
              <p className="font-ar mt-3 text-xs text-ink-muted">
                هذه الرحلة مغلقة (محجوزة أو ملغاة) ولا يمكن إعادة إرسالها.
              </p>
            ) : (
              <>
                <p className="font-ar mt-1 text-xs text-ink-muted">
                  أنشئ رابطًا موقّعًا صالحًا لمدة 72 ساعة، ثم انسخه إلى واتساب
                  المشغّل يدويًا.
                </p>
                {dispatchExpired && trip.dispatch_nonce && (
                  <p className="font-ar mt-3 rounded-md border border-amber-400/40 bg-amber-500/10 p-2 text-xs text-amber-200">
                    انتهت صلاحية الرابط السابق. أعِد الإرسال لتوليد رابط جديد.
                  </p>
                )}
                <div className="mt-4">
                  <DispatchForm
                    tripRequestId={trip.id}
                    initialOperatorPhone={trip.dispatch_target_phone}
                    initialExpiresAt={trip.dispatch_expires_at}
                  />
                </div>
              </>
            )}
          </div>
        </aside>
      </div>
    </section>
  );
}

// ============================================================================
// Phase 5 view — gated behind PHASE5_ADMIN_UI=true
// ============================================================================

async function Phase5TripView({ trip }: { trip: TripRequestRow }) {
  // Phase 5 reads, in parallel:
  //   - unified offers list (Phase 4 + Phase 5 merged + tagged)
  //   - current round's still-pending targets (refresh-durable
  //     source for the operator URL cards — see acceptance #14a)
  const [offers, currentTargets] = await Promise.all([
    listOffersByTripUnified(trip.id),
    listCurrentRoundTargets(trip.id),
  ]);

  // Sort offers: pending first (so admin focuses on actionable
  // items), then by total_price_sar ascending within each
  // group, then by created_at DESC as tiebreaker. Spec
  // acceptance #17 (price-ascending default).
  const sortedOffers = [...offers].sort((a, b) => {
    if (a.status === 'pending' && b.status !== 'pending') return -1;
    if (b.status === 'pending' && a.status !== 'pending') return 1;
    if (a.total_price_sar !== b.total_price_sar) {
      return a.total_price_sar - b.total_price_sar;
    }
    return a.created_at < b.created_at ? 1 : -1;
  });

  const isClosed = trip.status === 'booked' || trip.status === 'cancelled';
  const tripIsOffered = trip.status === 'offered';

  // Rebuild current-round dispatch URLs from the persisted target
  // rows. Uses issueOperatorTokenFromTarget (PR 2) which derives
  // issued_at from target.sent_at exclusively — so the URLs
  // reproduce byte-identically across page renders even if the
  // original Server Action's response was lost.
  const currentDispatches: DispatchPanelV2Props['currentDispatches'] =
    currentTargets.map((target) => {
      const issued = issueOperatorTokenFromTarget({
        trip_request_id: target.trip_request_id,
        id: target.id,
        nonce: target.nonce,
        sent_at: target.sent_at,
        expires_at: target.expires_at,
      });
      const operatorUrl = buildOperatorUrl(issued.token);
      return {
        target_id: target.id,
        target_phone: target.target_phone,
        operator_url: operatorUrl,
        whatsapp_link: buildOperatorWhatsAppLink(target.target_phone, operatorUrl),
        sent_at: target.sent_at,
        expires_at: target.expires_at,
      };
    });

  return (
    <section>
      <div className="flex items-center justify-between gap-3">
        <BackLink />
        <AddonsTabLink tripId={trip.id} />
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1.6fr,1fr] lg:items-start">
        <div className="space-y-6">
          <TripDetailCard trip={trip} />

          <div className="rounded-xl border border-border bg-navy-card/40 p-6">
            <div className="flex items-center justify-between gap-3">
              <h3 className="font-ar text-base font-medium text-ink">
                العروض المستلمة ({sortedOffers.length})
              </h3>
            </div>
            {sortedOffers.length === 0 ? (
              <p className="font-ar mt-4 rounded-md border border-dashed border-border bg-navy-secondary/30 p-6 text-center text-sm text-ink-muted">
                لم يصل أي عرض من المشغّلين بعد.
              </p>
            ) : (
              <div className="mt-4 space-y-4">
                {sortedOffers.map((offer) => (
                  <UnifiedOfferCard
                    key={`${offer.source}:${offer.id}`}
                    offer={offer}
                    tripIsOffered={tripIsOffered}
                  />
                ))}
              </div>
            )}
          </div>
        </div>

        <aside className="space-y-6">
          <div className="rounded-xl border border-border bg-navy-card/40 p-5">
            <h3 className="font-ar text-base font-medium text-ink">
              إرسال للمشغّلين
            </h3>
            <DispatchPanelV2
              tripRequestId={trip.id}
              isClosed={isClosed}
              currentDispatches={currentDispatches}
            />
          </div>
        </aside>
      </div>
    </section>
  );
}

function BackLink() {
  return (
    <Link
      href="/admin/trips"
      className="font-ar group inline-flex items-center gap-2 text-sm text-ink-muted transition-colors hover:text-gold"
    >
      <ArrowLeft
        className="h-4 w-4 transition-transform group-hover:translate-x-1 rtl:rotate-180"
        aria-hidden
      />
      العودة لقائمة الرحلات
    </Link>
  );
}

/**
 * Phase 6.2 PR 2b: small inline navigation to the per-trip
 * add-ons surface. Renders unconditionally; the addons page
 * itself handles the 3-case gate (pre-accept / Case B /
 * Case C / closed).
 */
function AddonsTabLink({ tripId }: { tripId: string }) {
  return (
    <Link
      href={`/admin/trips/${tripId}/addons`}
      className="font-ar group inline-flex items-center gap-2 rounded-md border border-gold/40 bg-gold/10 px-3 py-1.5 text-xs text-gold-light transition-colors hover:bg-gold/20"
    >
      الخدمات الإضافية ←
    </Link>
  );
}
